"""
Generates CombineDatFiles.ico for the Explorer context-menu entries.

Committed alongside the .ico so the icon is reproducible rather than an opaque
binary nobody can regenerate or adjust.

    python make_icon.py

Design notes
------------
The glyph is the conventional "merge" mark: two strokes on the left converging
into one on the right. It has to survive a 16x16 context menu, so each size is
drawn with pixel-aligned geometry at that size rather than by downsampling a
large master, which turns 2px strokes into grey mush.

The colour is a mid blue. Context menus can be light or dark depending on the
Windows theme, so the glyph avoids both white and black - either would vanish
against one of them.
"""
from PIL import Image, ImageDraw

ICO_PATH = 'CombineDatFiles.ico'
SIZES = [16, 20, 24, 32, 48, 64, 128, 256]

BLUE = (46, 134, 222, 255)       # reads on both light and dark menu backgrounds
BLUE_DARK = (30, 100, 175, 255)  # junction dot, a shade darker so it reads as a node


def draw_glyph(size: int) -> Image.Image:
    """Two inputs joining a spine and leaving as one, at this exact pixel size.

    Drawn with rectangles rather than lines: PIL centres a stroked line on the
    coordinate, which lands strokes on half-pixels and blurs a 16px glyph.
    Rectangles are inclusive and land exactly where told.

    An earlier version converged the two inputs with diagonals. At 16px those
    diagonals are 3px wide and read as a blob, so the shape is now an explicit
    spine, which stays unambiguous all the way down.
    """
    img = Image.new('RGBA', (size, size), (0, 0, 0, 0))
    d = ImageDraw.Draw(img)

    s = size / 16.0                       # scale from the 16px reference design

    def px(v):
        return round(v * s)

    def bar(x0, y0, x1, y1, fill=BLUE):
        # -1 keeps the nominal width: a rect from 2..4 is 3px, we want 2.
        d.rectangle([px(x0), px(y0), px(x1) - 1, px(y1) - 1], fill=fill)

    #  ..####.........      two inputs on the left
    #  .....##........      joining a vertical spine
    #  .....######....      and leaving as a single output
    bar(2, 3, 8, 5)         # top input
    bar(2, 11, 8, 13)       # bottom input
    bar(6, 3, 8, 13)        # spine
    bar(6, 7, 14, 9)        # output

    # The junction sits a shade darker so the corner reads as a node rather than
    # a printing error, at sizes where there is room for it to show.
    if size >= 24:
        bar(6, 7, 8, 9, fill=BLUE_DARK)

    return img


def main():
    frames = [draw_glyph(n) for n in SIZES]
    # PIL writes a multi-resolution .ico from the largest image plus sizes; pass
    # the frames explicitly so each hand-drawn size is preserved rather than
    # regenerated by resampling.
    frames[-1].save(ICO_PATH, format='ICO',
                    sizes=[(n, n) for n in SIZES],
                    append_images=frames[:-1])
    print(f'wrote {ICO_PATH} with sizes: {", ".join(str(n) for n in SIZES)}')


if __name__ == '__main__':
    main()
